### ISSUE TITLE
Add a toggle button that directly scrolls the user to the top of the page 

### ISSUE THREAD

**Issue by yuyish** [yuyish/travelandtoursproject#6]
Please add a toggle button on the landing page.As the landing page is long when users scroll through the page user may find difficulty and time consuming scrolling upwards again to navigate through navbar.So keep a toggle button that directly scrolls the user to the top of page in a click.

**Comment by Bishal721** [comment]
I have successfully added the Scroll to top button so that user can directly scroll to the start of the page in a single click.
